### ISSUE TITLE
Can't override SignUp

### ISSUE THREAD

**Issue by michelem09** [Two-Lambda-Labs/amplify-react-router#3]
Hello,
thanks for this, very cool, but I have a problem trying to override SignUp.

This is my code:

```
import React, { Component } from 'react';
import './App.css';
import { CustomSignUp } from './CustomSignUp';

import AmplifyRouter from 'amplify-react-router';
import awsconfig from './aws-exports';
import { SignUp } from 'aws-amplify-react';

const theme = {
	formContainer: { 'margin': '2% 50px' },
	a: { color: 'var(--lightSquidInk)' },
};

const signUpConfig = {
	hiddenDefaults: ['phone_number']
};

class App extends Component {
	render() {
		return (
			<div className="App">
				<header className="App-header">
					Here header
				</header>
				<AmplifyRouter
					amplifyConfig={awsconfig}
					homeRoute="/"
					componentOverrides={[CustomSignUp]}
					theme={ theme }
				>
                                      <Page path="/" />
				</AmplifyRouter>
				<footer className="App-footer">
					Here footer
				</footer>
			</div>
		);
	}
}

export default App;

```

There are a couple of problems here:

1. The `SignIn` page hasn't the link to "Create account" anymore (but it works if you manually go to `/sign-up`)
2. How can I pass `signUpConfig` to `CustomSignUp`? I'd like to pass `{ hiddenDefaults: ['phone_number'] }`

![AwesomeScreenshot-localhost-sign-in-2019-08-14_9_37](https://user-images.githubusercontent.com/439555/63002895-459fd880-be77-11e9-971d-655c24758f6c.png)

**Comment by GoPro16** [comment]
Hey there!

1. It looks like that gets removed if the OG `SignUp` is set to hide for the overridden component. [Code Link](https://github.com/aws-amplify/amplify-js/blob/master/packages/aws-amplify-react/src/Auth/SignIn.jsx#L120)

2. At the time I didn't have a use case for it. if you want to add this support in I would suggest changing the `componentOverrides` array to accept either a component or an object containing the tag and additional props to spread onto the component. 

The current structure assumes there is no HOC on top of the overridden component. If there are only a few other over props that each of the components can take I don't see a problem as well with just adding it to the top level `AmplifyReactRouter` props and passing it directly to the component if it belongs to the correct one.

**Comment by michelem09** [comment]
I think they should add the routing built-in, it would be much easier, I will try something in the meantime. Thanks!
